komga:
  remember-me:
    key: changeMe!
    validity: 2592000 # 1 month
#  libraries-scan-cron: "*/5 * * * * ?" #every 5 seconds
  libraries-scan-cron: "-" #disable
  libraries-scan-startup: false
  database:
    file: ":memory:"
  cors.allowed-origins:
    - http://localhost:8081
  task-consumers: 5
  task-consumers-max: 20
#  file-hashing: false
#  delete-empty-collections: true
#  delete-empty-read-lists: true
spring:
  artemis:
    embedded:
      data-directory: ./artemis
logging:
  file:
    name: komga-dev.log
  level:
    org.apache.activemq.audit.message: WARN
    org.gotson.komga: DEBUG
#    org.jooq: DEBUG
#    web: DEBUG
#    com.zaxxer.hikari: DEBUG
#    org.springframework.jms: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG
  logback:
    rollingpolicy:
      max-history: 1

management.metrics.export.influx:
  #  enabled: true
  uri: http://localhost:8086

springdoc:
  cache:
    disabled: true

#server:
#  servlet:
#    context-path: /komga
